development:
      host:  pdckmminstance.cqm9gzsdjxi3.ap-southeast-1.rds.amazonaws.com
      adapter: mysql2
      database: pdckmm_dev
      port: 3306
      username: pdcuser
      password: p*(7)6U$
      encoding: utf8

test: &test
      host:  pdckmminstance.cqm9gzsdjxi3.ap-southeast-1.rds.amazonaws.com
      adapter: mysql2
      database: pdckmm_dev
      port: 3306
      username: pdcuser
      password: p*(7)6U$
      encoding: utf8

production:
      host: pdckmminstance.cqm9gzsdjxi3.ap-southeast-1.rds.amazonaws.com
      adapter: mysql2
      database: pdckmmdb
      port: 3306
      username: pdcuser
      password: p*(7)6U$
      encoding: utf8
cucumber:
  <<: *test
